import {
	HomeIcon as HomeOutline,
	UserGroupIcon as UsersOutline,
	FolderIcon as FolderOutline,
	ClipboardDocumentListIcon as TasksOutline,
	CalendarIcon as CalendarOutline,
	AcademicCapIcon as TrainingOutline,
	UserPlusIcon as RecruitmentOutline,
	ChartBarIcon as StatsOutline,
	Cog6ToothIcon as SettingsOutline,
	BellIcon as BellOutline,
	MagnifyingGlassIcon as SearchOutline,
	ArrowRightStartOnRectangleIcon as LogoutOutline,
	UserCircleIcon as ProfileOutline,
	BuildingOffice2Icon as GroupOutline,
	PlusIcon as PlusOutline,
	PencilIcon as EditOutline,
	TrashIcon as DeleteOutline,
	XMarkIcon as CloseOutline,
	CheckIcon as CheckOutline,
	ExclamationTriangleIcon as WarningOutline,
	InformationCircleIcon as InfoOutline,
	ExclamationCircleIcon as ErrorOutline,
	CheckCircleIcon as SuccessOutline,
	ChevronDownIcon as ChevronDownOutline,
	ChevronRightIcon as ChevronRightOutline,
	ChevronLeftIcon as ChevronLeftOutline,
	ChevronUpIcon as ChevronUpOutline,
	EllipsisVerticalIcon as MoreOutline,
	FunnelIcon as FilterOutline,
	ArrowsUpDownIcon as SortOutline,
	DocumentIcon as DocumentOutline,
	PaperClipIcon as AttachOutline,
	ClockIcon as ClockOutline,
	MapPinIcon as LocationOutline,
	TagIcon as TagOutline,
	LockClosedIcon as LockOutline,
	EyeIcon as EyeOutline,
	EyeSlashIcon as EyeSlashOutline,
	SunIcon as SunOutline,
	MoonIcon as MoonOutline,
	Bars3Icon as MenuOutline,
	ArrowLeftIcon as BackOutline,
	ArrowDownTrayIcon as DownloadOutline,
	ArrowUpTrayIcon as UploadOutline,
	ShieldCheckIcon as ShieldOutline,
	StarIcon as StarOutline,
	HeartIcon as HeartOutline,
	FlagIcon as FlagOutline,
	CalendarDaysIcon as CalendarDaysOutline,
	NoSymbolIcon as AbsenceOutline,
	ArrowPathIcon as RefreshOutline,
	DocumentTextIcon as FileOutline,
	LinkIcon as LinkOutline,
	PhoneIcon as PhoneOutline,
	EnvelopeIcon as MailOutline,
	GlobeAltIcon as GlobeOutline,
	ComputerDesktopIcon as DesktopOutline,
	DevicePhoneMobileIcon as MobileOutline,
	ArrowTrendingUpIcon as TrendUpOutline,
	ArrowTrendingDownIcon as TrendDownOutline,
	SparklesIcon as SparklesOutline,
	BriefcaseIcon as BriefcaseOutline,
	CurrencyEuroIcon as EuroOutline,
	WrenchScrewdriverIcon as ToolsOutline,
	ChatBubbleLeftEllipsisIcon as ChatOutline,
	VideoCameraIcon as VideoOutline,
	CpuChipIcon as BotOutline,
	NewspaperIcon as NewsOutline,
	ListBulletIcon as LogsOutline,
	BellAlertIcon as AlertOutline,
	LightBulbIcon as IdeaOutline,
	ChatBubbleBottomCenterTextIcon as CommunicationOutline,
	PaintBrushIcon as CreationOutline,
	DocumentDuplicateIcon as ContentOutline,
	RocketLaunchIcon as RocketOutline,
	SignalIcon as PingOutline,
} from "@heroicons/react/24/outline";

import {
	HomeIcon as HomeSolid,
	UserGroupIcon as UsersSolid,
	FolderIcon as FolderSolid,
	ClipboardDocumentListIcon as TasksSolid,
	CalendarIcon as CalendarSolid,
	AcademicCapIcon as TrainingSolid,
	UserPlusIcon as RecruitmentSolid,
	ChartBarIcon as StatsSolid,
	Cog6ToothIcon as SettingsSolid,
	BellIcon as BellSolid,
	MagnifyingGlassIcon as SearchSolid,
	UserCircleIcon as ProfileSolid,
	BuildingOffice2Icon as GroupSolid,
	PlusIcon as PlusSolid,
	CheckCircleIcon as SuccessSolid,
	ExclamationTriangleIcon as WarningSolid,
	ExclamationCircleIcon as ErrorSolid,
	InformationCircleIcon as InfoSolid,
	StarIcon as StarSolid,
	HeartIcon as HeartSolid,
	FlagIcon as FlagSolid,
	ShieldCheckIcon as ShieldSolid,
	NoSymbolIcon as AbsenceSolid,
	CpuChipIcon as BotSolid,
	NewspaperIcon as NewsSolid,
	BellAlertIcon as AlertSolid,
	RocketLaunchIcon as RocketSolid,
	SignalIcon as PingSolid,
} from "@heroicons/react/24/solid";

export const icons = {
	home: { outline: HomeOutline, solid: HomeSolid },
	users: { outline: UsersOutline, solid: UsersSolid },
	folder: { outline: FolderOutline, solid: FolderSolid },
	tasks: { outline: TasksOutline, solid: TasksSolid },
	calendar: { outline: CalendarOutline, solid: CalendarSolid },
	calendarDays: { outline: CalendarDaysOutline, solid: CalendarSolid },
	training: { outline: TrainingOutline, solid: TrainingSolid },
	recruitment: { outline: RecruitmentOutline, solid: RecruitmentSolid },
	stats: { outline: StatsOutline, solid: StatsSolid },
	settings: { outline: SettingsOutline, solid: SettingsSolid },
	bell: { outline: BellOutline, solid: BellSolid },
	search: { outline: SearchOutline, solid: SearchSolid },
	logout: { outline: LogoutOutline, solid: LogoutOutline },
	profile: { outline: ProfileOutline, solid: ProfileSolid },
	group: { outline: GroupOutline, solid: GroupSolid },
	plus: { outline: PlusOutline, solid: PlusSolid },
	edit: { outline: EditOutline, solid: EditOutline },
	delete: { outline: DeleteOutline, solid: DeleteOutline },
	close: { outline: CloseOutline, solid: CloseOutline },
	check: { outline: CheckOutline, solid: CheckOutline },
	warning: { outline: WarningOutline, solid: WarningSolid },
	info: { outline: InfoOutline, solid: InfoSolid },
	error: { outline: ErrorOutline, solid: ErrorSolid },
	success: { outline: SuccessOutline, solid: SuccessSolid },
	chevronDown: { outline: ChevronDownOutline, solid: ChevronDownOutline },
	chevronRight: { outline: ChevronRightOutline, solid: ChevronRightOutline },
	chevronLeft: { outline: ChevronLeftOutline, solid: ChevronLeftOutline },
	chevronUp: { outline: ChevronUpOutline, solid: ChevronUpOutline },
	more: { outline: MoreOutline, solid: MoreOutline },
	filter: { outline: FilterOutline, solid: FilterOutline },
	sort: { outline: SortOutline, solid: SortOutline },
	document: { outline: DocumentOutline, solid: DocumentOutline },
	attach: { outline: AttachOutline, solid: AttachOutline },
	clock: { outline: ClockOutline, solid: ClockOutline },
	location: { outline: LocationOutline, solid: LocationOutline },
	tag: { outline: TagOutline, solid: TagOutline },
	lock: { outline: LockOutline, solid: LockOutline },
	eye: { outline: EyeOutline, solid: EyeOutline },
	eyeSlash: { outline: EyeSlashOutline, solid: EyeSlashOutline },
	sun: { outline: SunOutline, solid: SunOutline },
	moon: { outline: MoonOutline, solid: MoonOutline },
	menu: { outline: MenuOutline, solid: MenuOutline },
	back: { outline: BackOutline, solid: BackOutline },
	download: { outline: DownloadOutline, solid: DownloadOutline },
	upload: { outline: UploadOutline, solid: UploadOutline },
	shield: { outline: ShieldOutline, solid: ShieldSolid },
	star: { outline: StarOutline, solid: StarSolid },
	heart: { outline: HeartOutline, solid: HeartSolid },
	flag: { outline: FlagOutline, solid: FlagSolid },
	absence: { outline: AbsenceOutline, solid: AbsenceSolid },
	refresh: { outline: RefreshOutline, solid: RefreshOutline },
	file: { outline: FileOutline, solid: FileOutline },
	link: { outline: LinkOutline, solid: LinkOutline },
	phone: { outline: PhoneOutline, solid: PhoneOutline },
	mail: { outline: MailOutline, solid: MailOutline },
	globe: { outline: GlobeOutline, solid: GlobeOutline },
	desktop: { outline: DesktopOutline, solid: DesktopOutline },
	mobile: { outline: MobileOutline, solid: MobileOutline },
	trendUp: { outline: TrendUpOutline, solid: TrendUpOutline },
	trendDown: { outline: TrendDownOutline, solid: TrendDownOutline },
	sparkles: { outline: SparklesOutline, solid: SparklesOutline },
	briefcase: { outline: BriefcaseOutline, solid: BriefcaseOutline },
	euro: { outline: EuroOutline, solid: EuroOutline },
	tools: { outline: ToolsOutline, solid: ToolsOutline },
	chat: { outline: ChatOutline, solid: ChatOutline },
	video: { outline: VideoOutline, solid: VideoOutline },
	bot: { outline: BotOutline, solid: BotSolid },
	news: { outline: NewsOutline, solid: NewsSolid },
	logs: { outline: LogsOutline, solid: LogsOutline },
	alert: { outline: AlertOutline, solid: AlertSolid },
	idea: { outline: IdeaOutline, solid: IdeaOutline },
	communication: { outline: CommunicationOutline, solid: CommunicationOutline },
	creation: { outline: CreationOutline, solid: CreationOutline },
	content: { outline: ContentOutline, solid: ContentOutline },
	rocket: { outline: RocketOutline, solid: RocketSolid },
	ping: { outline: PingOutline, solid: PingSolid },
} as const;

export type IconName = keyof typeof icons;
export type IconStyle = "outline" | "solid";

/**
 * Get an icon component
 * @param name -  Icon name
 * @param style - Outline
 */

export function getIcon(name: IconName, style: IconStyle = "outline") {
	return icons[name][style];
}
